# Generated by Django 3.0.5 on 2020-04-17 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chatterbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('enrolled', models.DateField()),
                ('last_booking', models.DateField()),
                ('credits_total', models.SmallIntegerField(default=10)),
                ('credits_balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='chatterbox.Course')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='chatterbox.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
