# Generated by Django 3.0.5 on 2020-04-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatterbox', '0002_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('language', 'level')},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ('enrolled',)},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('last_name', 'first_name')},
        ),
    ]
