# Generated by Django 3.0.5 on 2020-04-17 23:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chatterbox', '0003_auto_20200417_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('calculated_date', models.DateField(default=datetime.date.today)),
                ('on_track', models.IntegerField(default=0)),
                ('slow', models.IntegerField(default=0)),
                ('inactive', models.IntegerField(default=0)),
                ('lapsed', models.IntegerField(default=0)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='chatterbox.Course')),
                ('organisation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='chatterbox.Organisation')),
            ],
            options={
                'unique_together': {('calculated_date', 'organisation', 'course')},
            },
        ),
    ]
