# Generated by Django 3.0.5 on 2020-04-19 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatterbox', '0004_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='chatterbox.Course'),
        ),
    ]
